// Sync the package version into:
//   1. src/version-generated.js — the runtime VERSION export.
//   2. The pinned CDN URLs in README.md and docs/library-uses-in-code.md
//      so jsDelivr / unpkg examples always reference the current
//      published version. Both docs name the version explicitly so
//      a reader copy/pasting the snippet gets a deterministic load
//      rather than a moving `@latest`.
//
// Runs at `pretest` and `prepack` so a missed bump can't ride out
// to npm (`prepack`) or to a CI run (`pretest`).

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const pkg  = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const VERSION = pkg.version;

// 1. Runtime VERSION export.
const out = `// Generated by scripts/sync-version.mjs. Do not edit by hand.\nexport const VERSION = ${JSON.stringify(VERSION)};\n`;
fs.writeFileSync(path.join(root, 'src', 'version-generated.js'), out, 'utf8');
console.log('version-generated.js ->', VERSION);

// 2. CDN URL bumper. Rewrites every `@mmpworks/formbuilder-dsl@<x.y.z>`
//    occurrence inside the named docs. The regex is anchored on the
//    scoped package name so unrelated `@<version>` strings (npm
//    install snippets, peer-dep notes) stay untouched.
const CDN_RX = /@mmpworks\/formbuilder-dsl@\d+\.\d+\.\d+(-[a-zA-Z0-9.-]+)?/g;
const docsToBump = [
    'README.md',
    'docs/library-uses-in-code.md'
];
for (const rel of docsToBump) {
    const abs = path.join(root, rel);
    if (!fs.existsSync(abs)) {
        console.log(`${rel} -> (skipped; file not found)`);
        continue;
    }
    const before = fs.readFileSync(abs, 'utf8');
    const after  = before.replace(CDN_RX, `@mmpworks/formbuilder-dsl@${VERSION}`);
    if (before === after) {
        console.log(`${rel} -> (unchanged)`);
        continue;
    }
    fs.writeFileSync(abs, after, 'utf8');
    const matches = before.match(CDN_RX) ?? [];
    console.log(`${rel} -> bumped ${matches.length} CDN URL(s) to @${VERSION}`);
}
